---
title: "boxplot_Methods.Rmd"
author: "Virgilio Gonzenbach"
date: "8/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache= TRUE, 
                      fig.width = 10, 
                      fig.height = 7, 
                      dpi=300)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```



```{r load, include=FALSE}
myPaths = c(.libPaths(), "/home/vgonzenb/R/x86_64-pc-linux-gnu-library/4.0")
.libPaths(myPaths)
library(tidyverse) #dplyr, ggplot2, tidyr
library(reshape2)
library(ggthemes)

# Load data
load_data = function(size){
  
  path = sprintf('data/avg_cbf_vals_by_GMD_size-%s.csv', size)
  df = read.csv(path)
  colnames(df)[2] = "Method"
  colnames(df)[3:ncol(df)] = c("10-20%", "20-30%", "30-40%", "40-50%", "50-60%", "60-70%", "70-80%", "80-90%", "90-100%")
  df$Method = recode(df$Method, Raw = "Uncorrected", Ahlgren = "NWC")
  df$Method = factor(df$Method, levels = unique(df$Method))
  
  return(df)
}

df_r2 = load_data(2)
df_r3 = load_data(3)
df_r4 = load_data(4)
```

## Boxplots

### R = 2

```{r boxplot_r2}
# Plot Boxplot
df_r2 %>% pivot_longer(cols = c(-subjectID, -Method), names_to = "GMD_RANGE") %>% 
  ggplot(aes(x=GMD_RANGE, y=value, color = Method)) + 
  geom_boxplot(position = position_dodge(width = 0.9)) + ylab("AVERAGE CBF") + xlab("GMD RANGE") + 
  stat_summary(fun=mean, geom="line", 
               aes(group = Method, color = Method),
               position = position_dodge(width = 0.9)) +
  theme_classic() + scale_color_calc()
```

### R = 3

```{r boxplot_r3}
# Plot Boxplot
df_r3 %>% pivot_longer(cols = c(-subjectID, -Method), names_to = "GMD_RANGE") %>% 
  ggplot(aes(x=GMD_RANGE, y=value, color = Method)) + 
  geom_boxplot(position = position_dodge(width = 0.9)) + ylab("AVERAGE CBF") + xlab("GMD RANGE") + 
  stat_summary(fun=mean, geom="line", 
               aes(group = Method, color = Method),
               position = position_dodge(width = 0.9)) +
  theme_classic() + scale_color_calc()
```

### R = 4

```{r boxplot_r4}
# Plot Boxplot
df_r4 %>% pivot_longer(cols = c(-subjectID, -Method), names_to = "GMD_RANGE") %>% 
  ggplot(aes(x=GMD_RANGE, y=value, color = Method)) + 
  geom_boxplot(position = position_dodge(width = 0.9)) + ylab("AVERAGE CBF") + xlab("GMD RANGE") + 
  stat_summary(fun=mean, geom="line", 
               aes(group = Method, color = Method),
               position = position_dodge(width = 0.9)) +
  theme_classic() + scale_color_calc()
```



