---
title: "ISLA comparison: Visualizing Proportion significant P-values across ROIs"
author: "Virgilio Gonzenbach"
date: "6/18/2021"
output:
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      cache=TRUE, 
                      fig.width = 10, 
                      fig.height = 7, 
                      dpi=300)

knitr::opts_knit$set(root.dir = '/home/vgonzenb/ISLA/')
```

```{r, include=FALSE}
 # Set to my library
myPaths = c(.libPaths(), "/home/vgonzenb/R/x86_64-pc-linux-gnu-library/4.0")
.libPaths(myPaths)
library(ggplot2)
library(plyr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggthemes)
library(gridExtra)
library(stargazer)
library(flextable)
library(hash)

# Load data
p_df = read.csv('results/frac_sigPs_by_ROI_adjBy10thr.csv')
colnames(p_df)[1] = "METHOD"

# Separate first column
p_df$METHOD = c("Raw", "ISLA_R2", "ISLA_R3", "ISLA_R4", "Ahlgren_R2", "Ahlgren_R3", "Ahlgren_R4")
p_df = tidyr::separate(p_df, METHOD, into = c("method", "radius"), sep="_")

# Prep method
p_df$method = factor(p_df$method, levels=unique(p_df$method))

# Prep radius
p_df = p_df[rep(seq_len(nrow(p_df)), times = c(3,1,1,1,1,1,1)), ] # repeat Raw CBF 3 times to match
p_df[p_df$method == "Raw", "radius"] = c("R2", "R3", "R4") # fill in radius info for Raw CBF
p_df$radius = factor(p_df$radius) %>% recode_factor(R2 = "R = 2", R3 = "R = 3", R4 = "R = 4") # recode for plotting

# Load ROI dictionary
thresh_df = read.csv('results/frac_within_threshold_voxels_by_ROI.csv')
dict = readxl::read_xlsx("data/MUSE_ROI_Dict.xlsx", 1)
s_dict = dict[dict$ROI_INDEX %in% 2:300, ]
s_dict$ROI_INDEX = paste0("X", s_dict$ROI_INDEX)

jlf_dict = read.csv("data/jlf_lookup.csv")
roi_class = readRDS('roi_class.rds')

# Split dataframe ROI class
subset_roi_df = function(roi_df, roi_indexes){
  roi_df = p_df %>% select(method, radius, any_of(roi_indexes))
  return(roi_df)
}

get_roi_info = function(roi_index, info=c("name", "side", "tissue"), dict_type="MUSE"){
  #' Given ROI index return its name 
  
  if(dict_type == "MUSE"){
    roi_dict = s_dict
    h = hash()
    h[["name"]] = "ROI_NAME"
    h[["side"]] = "HEMISPHERE"
    h[["tissue"]] = "TISSUE_SEG"
  }
  
  col = h[[info]]
  rows = match(roi_index, roi_dict$ROI_INDEX)
  roi_info = unname(unlist(roi_dict[rows, col]))
  
  return(roi_info)
}
```

## Plots: Examining statistical significance across ROIs

```{r}
plot_regions = function(roi_df, title="", x_text_size=7){
  #' Plot barplots of proportion significant Ps in given ROI
    
  df_long = roi_df %>% pivot_longer(!c("method", "radius"), names_to = "ROI", values_to = "PROP. SIG. P-VALUES", names_ptypes = list(ROI = factor()))
  
  # Order ROIs by Raw CBF
  roi_order = df_long$`PROP. SIG. P-VALUES`[df_long$method == "Raw" & df_long$radius == "R = 2"] %>% order(decreasing = TRUE)
  df_long$ROI = factor(df_long$ROI, levels=levels(df_long$ROI)[roi_order])
  
  # Plot
  df_long %>% ggplot(aes(x=ROI, y=`PROP. SIG. P-VALUES`, fill=method)) + geom_bar(position = 'dodge', stat = 'identity') + 
    theme_classic() + 
    scale_fill_calc(name = "Method") + facet_wrap(~radius) + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=x_text_size)) + 
    ggtitle(title) + theme(plot.title = element_text(hjust = 0.5))
  
}
```

### Frontal (Left)

```{r frontal_l_plot}
frontal_side = get_roi_info(roi_class$Frontal, "side")

# Add new ROI class to roi_class list of indexes
roi_class[["Frontal L"]] = roi_class$Frontal[frontal_side == "Left"]

p_df %>% subset_roi_df(roi_class[["Frontal L"]]) %>% plot_regions(title = "Frontal (Left)", x_text_size = 8)
```

### Frontal (Right)

```{r frontal_r_plot}
roi_class[["Frontal R"]] = roi_class$Frontal[frontal_side == "Right"]
p_df %>% subset_roi_df(roi_class[["Frontal R"]]) %>% plot_regions(title = "Frontal (Right)", x_text_size = 8)
```

### Temporal

```{r temporal_plot}
p_df %>% subset_roi_df(roi_class[["Temporal"]]) %>% plot_regions(title = "Temporal", x_text_size = 9)
```

### Parietal

```{r parietal_plot}
p_df %>% subset_roi_df(roi_class[["Parietal"]]) %>% plot_regions(title = "Parietal", x_text_size = 9)
```

### Occipital

```{r occipital_plot}
p_df %>% subset_roi_df(roi_class[["Occipital"]]) %>% plot_regions(title = "Occipital", 9)
```

### Deep

```{r deep_plot}
p_df %>% subset_roi_df(roi_class[["Deep"]]) %>% plot_regions(title = "Deep", 9)
```

### Limbic

```{r limbic_plot}
p_df %>% subset_roi_df(roi_class[["Limbic"]]) %>% plot_regions(title = "Limbic", 9)
```


